/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'reservedDate' : IDL.Text,
  'reservedTime' : IDL.Text,
  'message' : IDL.Text,
  'partySize' : IDL.Nat,
  'phone' : IDL.Text,
});
export const BusinessInfo = IDL.Record({
  'hours' : IDL.Text,
  'address' : IDL.Text,
  'rating' : IDL.Nat,
  'phone' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPopular' : IDL.Bool,
  'priceRange' : IDL.Text,
  'category' : IDL.Text,
});
export const Review = IDL.Record({
  'published' : IDL.Bool,
  'text' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getMenuCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getPopularMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getSubmissionById' : IDL.Func([IDL.Nat], [Submission], ['query']),
  'init' : IDL.Func([], [], []),
  'submitForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'reservedDate' : IDL.Text,
    'reservedTime' : IDL.Text,
    'message' : IDL.Text,
    'partySize' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const BusinessInfo = IDL.Record({
    'hours' : IDL.Text,
    'address' : IDL.Text,
    'rating' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPopular' : IDL.Bool,
    'priceRange' : IDL.Text,
    'category' : IDL.Text,
  });
  const Review = IDL.Record({
    'published' : IDL.Bool,
    'text' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getMenuCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getPopularMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getPublishedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getSubmissionById' : IDL.Func([IDL.Nat], [Submission], ['query']),
    'init' : IDL.Func([], [], []),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };