/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessInfo {
  'hours' : string,
  'address' : string,
  'rating' : bigint,
  'phone' : string,
}
export interface MenuItem {
  'name' : string,
  'description' : string,
  'isPopular' : boolean,
  'priceRange' : string,
  'category' : string,
}
export interface Review {
  'published' : boolean,
  'text' : string,
  'rating' : bigint,
  'reviewer' : string,
}
export interface Submission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'reservedDate' : string,
  'reservedTime' : string,
  'message' : string,
  'partySize' : bigint,
  'phone' : string,
}
export interface _SERVICE {
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getBusinessInfo' : ActorMethod<[], BusinessInfo>,
  'getMenuCategories' : ActorMethod<[], Array<string>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getPopularMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getPublishedReviews' : ActorMethod<[], Array<Review>>,
  'getSubmissionById' : ActorMethod<[bigint], Submission>,
  'init' : ActorMethod<[], undefined>,
  'submitForm' : ActorMethod<
    [string, string, string, string, string, bigint, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];